# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgterm < Formula
  desc "PostgreSQL CLI like MySQL"
  homepage "https://github.com/mattb2401/pgterm"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattb2401/pgterm/releases/download/v1.0.3/pgterm_Darwin_x86_64.tar.gz"
      sha256 "6e3fd1cce6fd0b57f4d329317216657640c1de69b55c9a61d314f5015e4c6e67"

      def install
        bin.install "pgterm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattb2401/pgterm/releases/download/v1.0.3/pgterm_Darwin_arm64.tar.gz"
      sha256 "f0c9c56e6d84fc58b1bcc137fc2eafeffdf8d500dbe494bb00b80cb52865e7a5"

      def install
        bin.install "pgterm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mattb2401/pgterm/releases/download/v1.0.3/pgterm_Linux_x86_64.tar.gz"
      sha256 "a4455580b5d64cf6fed3ac38613703c40a135c19b2e82c55ea9d2db4f1c09f8a"
      def install
        bin.install "pgterm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mattb2401/pgterm/releases/download/v1.0.3/pgterm_Linux_arm64.tar.gz"
      sha256 "bac19398ed4848eb35c9f588a0f0edef28fd81a64ada0120878e65a5e92a0c3f"
      def install
        bin.install "pgterm"
      end
    end
  end

  test do
    system "#{bin}/pgterm", "--help"
  end
end
