# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgterm < Formula
  desc "PostgreSQL CLI like MySQL"
  homepage "https://github.com/mattb2401/pgterm"
  version "1.2.5"

  on_macos do
    on_intel do
      url "https://github.com/mattb2401/pgterm/releases/download/v1.2.5/pgterm_1.2.5_darwin_amd64.tar.gz"
      sha256 "cc64102d52f72af611c29402d8c86a966218bd2f17906826a26b5bda5def914a"

      def install
        bin.install "pgterm"
      end
    end
    on_arm do
      url "https://github.com/mattb2401/pgterm/releases/download/v1.2.5/pgterm_1.2.5_darwin_arm64.tar.gz"
      sha256 "b268bf71df7ea20697678f92ffdcaa39a5bfb7907dc49422038ad149a40a6d02"

      def install
        bin.install "pgterm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattb2401/pgterm/releases/download/v1.2.5/pgterm_1.2.5_linux_amd64.tar.gz"
        sha256 "bbb363621f7f415e57614bebda6878edeec4835079eb6b9d6b1b1b960eced3ca"

        def install
          bin.install "pgterm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattb2401/pgterm/releases/download/v1.2.5/pgterm_1.2.5_linux_arm64.tar.gz"
        sha256 "4ca9fa51b6eb7ab48fd1b1f40b5791ca853d942f54f9cccea021935fb353f024"

        def install
          bin.install "pgterm"
        end
      end
    end
  end

  test do
    system "#{bin}/pgterm", "--help"
  end
end
