# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgterm < Formula
  desc "PostgreSQL CLI like MySQL"
  homepage "https://github.com/mattb2401/pgterm"
  version "1.2.4"

  on_macos do
    on_intel do
      url "https://github.com/mattb2401/pgterm/releases/download/v1.2.4/pgterm_1.2.4_darwin_amd64.tar.gz"
      sha256 "b5544cb8973eaff4e45356b0bca23a5454215f70516e616ee997502317a9ccaf"

      def install
        bin.install "pgterm"
      end
    end
    on_arm do
      url "https://github.com/mattb2401/pgterm/releases/download/v1.2.4/pgterm_1.2.4_darwin_arm64.tar.gz"
      sha256 "3b6d66a5ab0bd124336a23dfbf49648cfefa8189ca6b5510ba97c130d5d1fd5e"

      def install
        bin.install "pgterm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattb2401/pgterm/releases/download/v1.2.4/pgterm_1.2.4_linux_amd64.tar.gz"
        sha256 "ba8e872fab265d0f827a85916dba5b69688a8d29d8dd0c7b55b72086f22c918a"

        def install
          bin.install "pgterm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattb2401/pgterm/releases/download/v1.2.4/pgterm_1.2.4_linux_arm64.tar.gz"
        sha256 "ac7959bf8d4f633dc5be46ee0575d1ae2198a7757c86b8a62c6ae83fa6c9d7c8"

        def install
          bin.install "pgterm"
        end
      end
    end
  end

  test do
    system "#{bin}/pgterm", "--help"
  end
end
